version: "3.9"
services:
  db:
    container_name: db-chamelo
    image: mysql:8.0
    ports:
      - "2000:3306"
    volumes:
      #- $PWD/db-data:/var/lib/mysql
      - ./db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: chamelo_db
      MYSQL_USER: laravel
      MYSQL_PASSWORD: laravel1234
    networks:
      - net-chamelo
  web:
    container_name: chamelo-web
    depends_on:
      - db
    ports:
      - "2002:80"
    volumes:
      #- "$PWD/web:/var/www/html"
      #- "$PWD/httpd.conf:/etc/httpd/conf/httpd.conf"
      - "./web:/var/www/html"
      - "./httpd.conf:/etc/httpd/conf/httpd.conf"
    image: laravel-php8
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - net-chamelo
networks:
  net-chamelo:
    
